name: Auto Merge PR

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Auto Merge
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_METHOD: squash
          MERGE_DELETE_BRANCH: "true"
